<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="updateSeverity" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOACS/IoTDFS_UpdateIncident/updateSeverity" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOACS/IoTDFS_UpdateIncident/updateSeverity" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateSeverity" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="updateSeverity_plt">
      <plt:role name="updateSeverity_role">
         <plt:portType name="tns:updateSeverity_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateSeverity" schemaLocation="../Schemas/updateSeverity_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CrmIncidentCollection_msg">
      <wsdl:part name="CrmIncidentCollection" element="top:CrmIncidentCollection"/>
   </wsdl:message>
   <wsdl:portType name="updateSeverity_ptt">
      <wsdl:operation name="update">
         <wsdl:input message="tns:CrmIncidentCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
