<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="deviceReadingInsert" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DEVICE_READING/IoTDFS2_IoTDeviceReadingSync/deviceReadingInsert" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DEVICE_READING/IoTDFS2_IoTDeviceReadingSync/deviceReadingInsert" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/deviceReadingInsert" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="deviceReadingInsert_plt">
      <plt:role name="deviceReadingInsert_role">
         <plt:portType name="tns:deviceReadingInsert_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/deviceReadingInsert" schemaLocation="../Schemas/deviceReadingInsert_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="DeviceReadingsCollection_msg">
      <wsdl:part name="DeviceReadingsCollection" element="top:DeviceReadingsCollection"/>
   </wsdl:message>
   <wsdl:portType name="deviceReadingInsert_ptt">
      <wsdl:operation name="insert">
         <wsdl:input message="tns:DeviceReadingsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
