<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="insertOTARecord" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOACS/IoTDFS2_OTAUpdate/insertOTARecord" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOACS/IoTDFS2_OTAUpdate/insertOTARecord" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertOTARecord" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="insertOTARecord_plt">
      <plt:role name="insertOTARecord_role">
         <plt:portType name="tns:insertOTARecord_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertOTARecord" schemaLocation="../Schemas/insertOTARecord_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="DeviceOtaUpdatesCollection_msg">
      <wsdl:part name="DeviceOtaUpdatesCollection" element="top:DeviceOtaUpdatesCollection"/>
   </wsdl:message>
   <wsdl:portType name="insertOTARecord_ptt">
      <wsdl:operation name="merge">
         <wsdl:input message="tns:DeviceOtaUpdatesCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
