<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="updateExistingIncidents" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOACS/IoTDFS2_OTAUpdate/updateExistingIncidents" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOACS/IoTDFS2_OTAUpdate/updateExistingIncidents" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/updateExistingIncidents" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="updateExistingIncidents_plt">
      <plt:role name="updateExistingIncidents_role">
         <plt:portType name="tns:updateExistingIncidents_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateExistingIncidents" schemaLocation="../Schemas/updateExistingIncidents.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="updateExistingIncidentsInput_msg">
      <wsdl:part name="updateExistingIncidentsInput_msg" element="db:updateExistingIncidentsInput"/>
   </wsdl:message>
   <wsdl:portType name="updateExistingIncidents_ptt">
      <wsdl:operation name="updateExistingIncidents">
         <wsdl:input message="tns:updateExistingIncidentsInput_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
